// ═══ Cross-language paradigm mappings — 8 bidirectional maps with concrete API translations ═══

export var PARADIGM_MAPS = {
  "python→javascript": {
    title: "Python → JavaScript/Node.js",
    stdlib: [
      "print('x') / print(x,end='') → console.log('x') / process.stdout.write(x)",
      "print(x, file=sys.stderr) → console.error(x)",
      "urllib2.urlopen(url) → fetch(url) or axios.get(url)",
      "urllib2.Request(url,data,headers) → fetch(url, {method:'POST',headers,body:JSON.stringify(data)})",
      "requests.get(url) → await fetch(url).then(r=>r.json())",
      "requests.post(url,json=data) → await fetch(url,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})",
      "json.loads(s) → JSON.parse(s)",
      "json.dumps(o) / json.dumps(o,indent=2) → JSON.stringify(o) / JSON.stringify(o,null,2)",
      "ConfigParser → JSON config file, dotenv, or cosmiconfig",
      "os.path.exists(p) → fs.existsSync(p)",
      "os.path.join(a,b) → path.join(a,b)",
      "os.path.basename(p) / os.path.dirname(p) → path.basename(p) / path.dirname(p)",
      "os.path.splitext(f) → [path.basename(f,path.extname(f)),path.extname(f)]",
      "os.makedirs(p,exist_ok=True) → fs.mkdirSync(p,{recursive:true})",
      "os.listdir(p) → fs.readdirSync(p)",
      "os.walk(p) → fs.readdirSync(p,{recursive:true,withFileTypes:true}) (Node 20+)",
      "pathlib.Path(f).read_text() → fs.readFileSync(f,'utf8')",
      "pathlib.Path(f).write_text(s) → fs.writeFileSync(f,s,'utf8')",
      "pathlib.Path(f).exists() → fs.existsSync(f)",
      "pathlib.Path(a) / b → path.join(a,b)",
      "open(f,'r').read() → fs.readFileSync(f,'utf8') or await fs.promises.readFile(f,'utf8')",
      "open(f,'w').write(s) → fs.writeFileSync(f,s) or await fs.promises.writeFile(f,s)",
      "open(f,'rb') → fs.readFileSync(f) (returns Buffer)",
      "time.strftime('%Y-%m-%d') → new Date().toISOString().slice(0,10)",
      "time.time() → Date.now()/1000",
      "time.sleep(n) → await new Promise(r=>setTimeout(r,n*1000))",
      "datetime.now() → new Date()",
      "datetime.now().isoformat() → new Date().toISOString()",
      "datetime.strptime(s,fmt) → new Date(s) or dayjs(s,fmt)",
      "timedelta(days=n) → n*24*60*60*1000 (ms) or dayjs().add(n,'day')",
      "sys.argv → process.argv.slice(2)",
      "sys.exit(code) → process.exit(code)",
      "os.environ['KEY'] / os.environ.get('KEY',def) → process.env.KEY || def",
      "re.match(pat,s) → s.match(new RegExp(pat))",
      "re.search(pat,s) → new RegExp(pat).exec(s)",
      "re.findall(pat,s) → [...s.matchAll(new RegExp(pat,'g'))].map(m=>m[0])",
      "re.sub(pat,repl,s) → s.replace(new RegExp(pat,'g'),repl)",
      "re.compile(pat) → new RegExp(pat,'g')",
      "re.split(pat,s) → s.split(new RegExp(pat))",
      "collections.Counter(items) → items.reduce((m,x)=>(m[x]=(m[x]||0)+1,m),{})",
      "collections.defaultdict(list) → new Proxy({},{get:(t,k)=>(t[k]=t[k]||[],t[k])})",
      "collections.OrderedDict → Map() (preserves insertion order)",
      "collections.deque → array (use push/shift for FIFO, push/pop for LIFO)",
      "collections.namedtuple('P',['x','y']) → class P { constructor(x,y){this.x=x;this.y=y} }",
      "itertools.chain(*lists) → [...list1,...list2,...listN] or [].concat(...lists)",
      "itertools.product(a,b) → a.flatMap(x=>b.map(y=>[x,y]))",
      "itertools.combinations(arr,r) → custom generator or combinatorics lib",
      "itertools.zip_longest(a,b,fill=0) → Array.from({length:Math.max(a.length,b.length)},(_,i)=>[a[i]??0,b[i]??0])",
      "functools.reduce(fn,items,init) → items.reduce(fn,init)",
      "functools.partial(fn,a) → fn.bind(null,a) or (b)=>fn(a,b)",
      "functools.lru_cache → manual Map cache or memoize lib",
      "hashlib.sha256(s.encode()).hexdigest() → crypto.createHash('sha256').update(s).digest('hex')",
      "base64.b64encode(s.encode()).decode() → Buffer.from(s).toString('base64')",
      "base64.b64decode(s) → Buffer.from(s,'base64').toString()",
      "uuid.uuid4() → crypto.randomUUID()",
      "copy.deepcopy(obj) → structuredClone(obj)",
      "copy.copy(obj) → {...obj} (shallow spread)",
      "math.floor/ceil/round → Math.floor/ceil/round",
      "math.sqrt/pow/log → Math.sqrt/pow/log",
      "random.random() → Math.random()",
      "random.randint(a,b) → Math.floor(Math.random()*(b-a+1))+a",
      "random.choice(arr) → arr[Math.floor(Math.random()*arr.length)]",
      "random.shuffle(arr) → arr.sort(()=>Math.random()-0.5) or Fisher-Yates",
      "logging.info/error/debug → console.log/error/debug or winston/pino logger",
      "subprocess.run(cmd) → child_process.execSync(cmd) or execa(cmd)",
      "typing.Optional[T] → T|undefined or T|null",
      "Decimal(x) → decimal.js lib or native arithmetic",
      "string.Template('$name') → template literal"
    ],
    patterns: [
      "class Foo: def __init__(self) → class Foo { constructor() }",
      "self.x → this.x (EVERY instance reference)",
      "def method(self,a,b) → method(a,b) { ... } (drop self)",
      "@staticmethod def fn() → static fn() { }",
      "@classmethod def fn(cls) → static fn() { }",
      "@property def name(self) → get name() { return this._name; }",
      "@name.setter def name(self,v) → set name(v) { this._name=v; }",
      "__str__(self) / __repr__(self) → toString() { }",
      "__len__(self) → get length() { } or custom method",
      "__eq__(self,other) → equals(other) { } (no operator overloading)",
      "__getitem__(self,key) → Proxy with get trap or get(key) method",
      "__contains__(self,item) → has(item) method",
      "__iter__/__next__ → [Symbol.iterator]() { } generator",
      "@dataclass class Foo: x:int; y:str → class Foo { constructor(x,y){this.x=x;this.y=y} }",
      "for k,v in dict.iteritems() → for (const [k,v] of Object.entries(dict))",
      "for k,v in dict.items() → for (const [k,v] of Object.entries(dict))",
      "dict.has_key(k) / k in dict → k in obj / obj.hasOwnProperty(k)",
      "isinstance(x, str) / isinstance(x, basestring) → typeof x === 'string'",
      "isinstance(x, (int,float,long)) → typeof x === 'number'",
      "isinstance(x,list) → Array.isArray(x)",
      "isinstance(x,dict) → typeof x==='object'&&x!==null&&!Array.isArray(x)",
      "isinstance(x,bool) → typeof x === 'boolean'",
      "isinstance(x,tuple) → Array.isArray(x) (Object.freeze for immutability)",
      "list.append(x) → array.push(x)",
      "list.extend(other) → array.push(...other)",
      "list.insert(i,x) → array.splice(i,0,x)",
      "list.pop() / list.pop(i) → array.pop() / array.splice(i,1)[0]",
      "list.remove(x) → array.splice(array.indexOf(x),1)",
      "list.index(x) → array.indexOf(x) (-1 vs ValueError)",
      "list.count(x) → array.filter(i=>i===x).length",
      "list.reverse() → array.reverse() (mutates) or [...arr].reverse()",
      "list(set(items)) → [...new Set(items)]",
      "dict.get(k,default) → obj[k] ?? default",
      "dict.setdefault(k,v) → obj[k] = obj[k] ?? v",
      "dict.update(other) → Object.assign(obj,other) or {...obj,...other}",
      "dict.pop(k,default) → (v=obj[k]??default, delete obj[k], v)",
      "'x' in list → array.includes('x')",
      "'x' in dict → 'x' in obj || obj.hasOwnProperty('x')",
      "[x*2 for x in items] → items.map(x=>x*2)",
      "[x for x in items if x>0] → items.filter(x=>x>0)",
      "[f(x) for x in items if p(x)] → items.filter(p).map(f)",
      "{k:v for k,v in items} → Object.fromEntries(items.map(([k,v])=>[k,v]))",
      "{k:f(v) for k,v in d.items()} → Object.fromEntries(Object.entries(d).map(([k,v])=>[k,f(v)]))",
      "set comprehension {x for x in items} → new Set(items.map(x=>x))",
      "generator (x for x in items) → function*(){for(const x of items)yield x}()",
      "def gen(): yield x → function* gen() { yield x }",
      "yield from iterable → yield* iterable",
      "next(gen) → gen.next().value",
      "try/except Exception as e → try { } catch(e) { }",
      "except (TypeError,ValueError) → catch(e) { if(e instanceof TypeError||e instanceof RangeError) }",
      "with open(f) as fh: → const data=fs.readFileSync(f,'utf8') or try/finally",
      "with contextmanager → try { acquire(); ... } finally { release(); }",
      "raise ValueError('msg') → throw new Error('msg')",
      "raise CustomError(msg) from e → throw new CustomError(msg,{cause:e})",
      "None → null",
      "True / False → true / false",
      "lambda x: x+1 → (x)=>x+1",
      "def fn(a,b=10,*args,**kwargs) → function fn(a,b=10,...args) (kwargs as options obj)",
      "f'Hello {name}' / '%s'%name → `Hello ${name}` (template literal)",
      "f'{val:.2f}' → val.toFixed(2)",
      "f'{val:>10}' → val.toString().padStart(10)",
      "a,b = b,a → [a,b]=[b,a]",
      "a,b,c = tuple_val → const [a,b,c] = array_val",
      "x if cond else y → cond ? x : y",
      "sorted(list,key=lambda x:x.v) → [...list].sort((a,b)=>a.v-b.v)",
      "sorted(list,reverse=True) → [...list].sort((a,b)=>b-a)",
      "dict.keys()/values()/items() → Object.keys/values/entries(obj)",
      "enumerate(items) → items.map((item,i)=>[i,item]) or forEach((item,i)=>{})",
      "zip(a,b) → a.map((x,i)=>[x,b[i]])",
      "any(cond for x in items) → items.some(x=>cond)",
      "all(cond for x in items) → items.every(x=>cond)",
      "sum(items) → items.reduce((s,x)=>s+x,0)",
      "min(items)/max(items) → Math.min(...items)/Math.max(...items)",
      "abs(x) → Math.abs(x)",
      "round(x,n) → Number(x.toFixed(n))",
      "divmod(a,b) → [Math.floor(a/b),a%b]",
      "int(s,base) → parseInt(s,base)",
      "str.startswith/endswith → str.startsWith/endsWith",
      "str.strip()/lstrip()/rstrip() → str.trim()/trimStart()/trimEnd()",
      "str.split(sep,maxsplit) → str.split(sep) (different maxsplit semantics!)",
      "'sep'.join(list) → array.join('sep')",
      "str.replace(old,new) → str.replaceAll(old,new) (ES2021+)",
      "str.upper()/lower() → str.toUpperCase()/toLowerCase()",
      "str.isdigit()/isalpha() → /^\\d+$/.test(str) / /^[a-zA-Z]+$/.test(str)",
      "str.zfill(n) → str.padStart(n,'0')",
      "chr(n)/ord(c) → String.fromCharCode(n)/c.charCodeAt(0)",
      "map(fn,items) → items.map(fn)",
      "filter(fn,items) → items.filter(fn)",
      "len(x) → x.length",
      "range(n) → Array.from({length:n},(_,i)=>i)",
      "range(a,b) → Array.from({length:b-a},(_,i)=>i+a)",
      "type(x).__name__ → typeof x or x.constructor.name",
      "ABC/@abstractmethod → throw new Error('Abstract') in base",
      "super().__init__() → super()",
      "multiple inheritance class C(A,B) → mixin pattern or single extends",
      "enum.Enum → Object.freeze({A:'A',B:'B'}) or TS enum"
    ],
    modules: [
      "from module import Class → import { Class } from {./module.js}",
      "from module import * → import * as module from {./module.js}",
      "import module → import module from {./module.js} (default)",
      "__name__=='__main__' → top-level await in ESM or if(require.main===module)",
      "__init__.py barrel → index.js with re-exports: export { X } from {./x.js}",
      "from .sibling import X → import { X } from {./sibling.js}",
      "from package.sub import X → import { X } from {./sub/index.js}",
      "requirements.txt / pyproject.toml → package.json dependencies",
      "pip install pkg → npm install pkg"
    ],
    async: [
      "urllib2.urlopen (sync) → await fetch() (async)",
      "open().read() (sync I/O) → await fs.promises.readFile() (async)",
      "time.sleep(n) (blocking) → await new Promise(r=>setTimeout(r,n*1000))",
      "threading.Thread(target=fn) → Promise or Worker thread",
      "multiprocessing.Pool → Promise.all() or worker_threads pool",
      "asyncio.run(main()) → top-level await or main().catch(console.error)",
      "async def fn(): await x → async function fn() { await x }",
      "asyncio.gather(*coros) → await Promise.all([p1,p2])",
      "asyncio.create_task(coro) → const p = asyncFn() (auto-starts)",
      "asyncio.Queue → custom async queue or p-queue lib",
      "async for item in aiter → for await (const item of asyncIter)"
    ],
    versionNotes: [
      "Target ES5: No arrow functions (use function(){}), no template literals (use +), no const/let (use var), no class (use prototype), no destructuring",
      "Target ES6/ES2015: Use const/let, arrow functions, template literals, classes, destructuring, default params, for...of, Map/Set, Promise",
      "Target ES2020: Use optional chaining (?.), nullish coalescing (??), BigInt, Promise.allSettled, globalThis, dynamic import()",
      "Target ES2024: Use Array.groupBy, Promise.withResolvers, Set operations, RegExp v flag, well-formed Unicode strings"
    ]
  },

  "javascript→python": {
    title: "JavaScript/Node.js → Python",
    stdlib: [
      "console.log(x) → print(x)",
      "console.error(x) → print(x, file=sys.stderr) or logging.error(x)",
      "console.warn(x) → logging.warning(x)",
      "console.table(data) → print(tabulate(data)) or pprint(data)",
      "fetch(url) → requests.get(url) (sync) or aiohttp (async) or urllib.request.urlopen(url)",
      "fetch(url,{method:'POST',body}) → requests.post(url,json=body)",
      "fetch(url,{headers}) → requests.get(url,headers=headers)",
      "response.json() → response.json() (requests) or json.loads(response.read())",
      "response.text() → response.text (requests) or response.read().decode()",
      "response.ok → response.ok (requests) or response.status == 200",
      "JSON.parse(s) → json.loads(s)",
      "JSON.stringify(obj) → json.dumps(obj)",
      "JSON.stringify(obj,null,2) → json.dumps(obj,indent=2)",
      "fs.readFileSync(f,'utf8') → Path(f).read_text() (pathlib) or open(f).read()",
      "fs.writeFileSync(f,s) → Path(f).write_text(s) or open(f,'w').write(s)",
      "fs.existsSync(p) → Path(p).exists() or os.path.exists(p)",
      "fs.mkdirSync(p,{recursive:true}) → Path(p).mkdir(parents=True,exist_ok=True)",
      "fs.readdirSync(p) → os.listdir(p) or list(Path(p).iterdir())",
      "fs.unlinkSync(f) → os.remove(f) or Path(f).unlink()",
      "fs.statSync(f).size → os.path.getsize(f) or Path(f).stat().st_size",
      "fs.promises.readFile(f) → async: await aiofiles.open(f) or sync: Path(f).read_text()",
      "path.join(a,b) → os.path.join(a,b) or Path(a)/b",
      "path.resolve(p) → os.path.abspath(p) or Path(p).resolve()",
      "path.basename(p) → os.path.basename(p) or Path(p).name",
      "path.dirname(p) → os.path.dirname(p) or Path(p).parent",
      "path.extname(p) → os.path.splitext(p)[1] or Path(p).suffix",
      "new Date() → datetime.now()",
      "new Date().toISOString() → datetime.now(timezone.utc).isoformat()",
      "Date.now() → int(time.time()*1000)",
      "new Date(s) → datetime.fromisoformat(s) (3.7+) or dateutil.parser.parse(s)",
      "setTimeout(fn,ms) → asyncio.sleep(ms/1000) or time.sleep(ms/1000)",
      "setInterval(fn,ms) → while loop with asyncio.sleep or threading.Timer",
      "clearTimeout/clearInterval → task.cancel() (asyncio) or timer.cancel()",
      "process.env.KEY → os.environ.get('KEY') or os.environ['KEY']",
      "process.argv.slice(2) → sys.argv[1:]",
      "process.cwd() → os.getcwd() or Path.cwd()",
      "process.exit(code) → sys.exit(code)",
      "Math.floor/ceil/round(x) → math.floor/ceil/round(x) or int(x)//1",
      "Math.random() → random.random()",
      "Math.max(...arr) / Math.min(...arr) → max(arr) / min(arr)",
      "Math.abs/sqrt/pow/log → abs/math.sqrt/math.pow/math.log (abs is builtin)",
      "x.length → len(x)",
      "String(x) → str(x)",
      "Number(x) → int(x) or float(x)",
      "parseInt(x,10) → int(x)",
      "parseFloat(x) → float(x)",
      "isNaN(x) → math.isnan(x)",
      "isFinite(x) → math.isfinite(x)",
      "crypto.createHash('sha256').update(s).digest('hex') → hashlib.sha256(s.encode()).hexdigest()",
      "crypto.randomUUID() → str(uuid.uuid4())",
      "Buffer.from(s,'base64') → base64.b64decode(s)",
      "Buffer.from(s).toString('base64') → base64.b64encode(s.encode()).decode()",
      "structuredClone(obj) → copy.deepcopy(obj)",
      "{...obj} (spread) → copy.copy(obj) or {**obj}",
      "new RegExp(pat,'g') → re.compile(pat)",
      "str.match(re) → re.match(pat,s) or re.search(pat,s)",
      "str.matchAll(re) → re.finditer(pat,s)",
      "str.replace(re,repl) → re.sub(pat,repl,s)",
      "str.split(re) → re.split(pat,s)",
      "new Map() → dict() (or OrderedDict for guaranteed order in 3.6)",
      "new Set() → set()",
      "new WeakMap() / new WeakRef(obj) → weakref.WeakValueDictionary() / weakref.ref(obj)",
      "child_process.execSync(cmd) → subprocess.run(cmd,shell=True,capture_output=True)",
      "EventEmitter → custom pub/sub or signals library"
    ],
    patterns: [
      "class Foo { constructor(a,b) { this.a=a } } → class Foo: def __init__(self,a,b): self.a=a",
      "this.x → self.x (EVERY instance reference)",
      "method(a,b) { } → def method(self,a,b): (add self as first param)",
      "static fn() { } → @staticmethod def fn():",
      "get name() { } → @property def name(self):",
      "set name(v) { } → @name.setter def name(self,v):",
      "toString() { } → def __str__(self):",
      "equals(other) → def __eq__(self,other):",
      "[Symbol.iterator]() → def __iter__(self): / def __next__(self):",
      "class Foo extends Bar → class Foo(Bar):",
      "#privateField → self._private_field (convention)",
      "class { static #count } → class Foo: _count = 0 (class variable)",
      "for (const [k,v] of Object.entries(obj)) → for k,v in obj.items():",
      "for (const item of array) → for item in array:",
      "for (let i=0;i<arr.length;i++) → for i in range(len(arr)):",
      "arr.forEach((item,i)=>{}) → for i,item in enumerate(arr):",
      "while (cond) { } → while cond:",
      "do { } while(cond) → while True: ... if not cond: break",
      "typeof x==='string' → isinstance(x,str)",
      "typeof x==='number' → isinstance(x,(int,float))",
      "typeof x==='boolean' → isinstance(x,bool)",
      "typeof x==='undefined' → x is None (or check with hasattr)",
      "Array.isArray(x) → isinstance(x,list)",
      "x instanceof Foo → isinstance(x,Foo)",
      "arr.push(x) → arr.append(x)",
      "arr.push(...other) → arr.extend(other)",
      "arr.pop() → arr.pop()",
      "arr.shift() → arr.pop(0) or collections.deque.popleft()",
      "arr.unshift(x) → arr.insert(0,x)",
      "arr.splice(i,1) → arr.pop(i) or del arr[i]",
      "arr.splice(i,0,x) → arr.insert(i,x)",
      "arr.slice(a,b) → arr[a:b]",
      "arr.concat(other) → arr + other or [*arr,*other]",
      "arr.includes(x) → x in arr",
      "arr.indexOf(x) → arr.index(x) (wrap in try for -1 behavior)",
      "arr.find(x=>cond) → next((x for x in arr if cond),None)",
      "arr.findIndex(x=>cond) → next((i for i,x in enumerate(arr) if cond),-1)",
      "arr.flat(depth) → [item for sub in arr for item in (sub if isinstance(sub,list) else [sub])]",
      "arr.flatMap(fn) → [y for x in arr for y in fn(x)]",
      "obj[k] ?? default → obj.get(k,default)",
      "Object.assign(obj,other) → obj.update(other) or {**obj,**other}",
      "Object.keys(obj) → list(obj.keys())",
      "Object.values(obj) → list(obj.values())",
      "Object.entries(obj) → obj.items()",
      "Object.fromEntries(arr) → dict(arr)",
      "Object.freeze(obj) → types.MappingProxyType(obj) or @dataclass(frozen=True)",
      "{...obj,key:val} → {**obj,'key':val}",
      "[...arr1,...arr2] → [*arr1,*arr2]",
      "arr.map(x=>x*2) → [x*2 for x in arr]",
      "arr.filter(x=>x>0) → [x for x in arr if x>0]",
      "arr.some(x=>cond) → any(cond for x in arr)",
      "arr.every(x=>cond) → all(cond for x in arr)",
      "arr.reduce((s,x)=>s+x,0) → sum(arr) or functools.reduce()",
      "[...arr].sort((a,b)=>a.v-b.v) → sorted(arr,key=lambda x:x.v)",
      "[...new Set(arr)] → list(set(arr))",
      "arr.join(sep) → sep.join(arr)",
      "str.startsWith(p) / str.endsWith(s) → str.startswith(p) / str.endswith(s)",
      "str.trim()/trimStart()/trimEnd() → str.strip()/lstrip()/rstrip()",
      "str.padStart(n,c) / str.padEnd(n,c) → str.rjust(n,c) / str.ljust(n,c)",
      "str.repeat(n) → str * n",
      "str.toUpperCase()/toLowerCase() → str.upper()/str.lower()",
      "str.replaceAll(old,new) → str.replace(old,new) (Python replace is global)",
      "str.charAt(i) / str[i] → str[i]",
      "str.charCodeAt(i) → ord(str[i])",
      "String.fromCharCode(n) → chr(n)",
      "try { } catch(e) { } → try: ... except Exception as e: ...",
      "catch(e) { if(e instanceof TypeError) } → except TypeError as e:",
      "throw new Error('msg') → raise ValueError('msg') or raise RuntimeError('msg')",
      "throw new CustomError(msg,{cause:e}) → raise CustomError(msg) from e",
      "null / undefined → None",
      "true / false → True / False",
      "(x)=>x+1 → lambda x: x+1",
      "function fn(a,b=10,...args) → def fn(a,b=10,*args):",
      "fn({opt1,opt2}) (options obj) → def fn(**kwargs): or def fn(opt1=None,opt2=None):",
      "`Hello ${name}` → f'Hello {name}'",
      "cond ? x : y → x if cond else y",
      "x?.y?.z → getattr(getattr(x,'y',None),'z',None) or try/except",
      "x ?? default → x if x is not None else default",
      "const {a,b}=obj → a,b = obj['a'],obj['b']",
      "const [a,b]=arr → a,b = arr",
      "const [first,...rest]=arr → first,*rest = arr",
      "switch(x) { case 'a': ... } → match x: case 'a': ... (3.10+) or if/elif",
      "function* gen() { yield x } → def gen(): yield x",
      "yield* iterable → yield from iterable",
      "for await (const x of iter) → async for x in iter:",
      "new Proxy(target,handler) → __getattr__/__setattr__/__getitem__ dunder methods",
      "Symbol('desc') → string constant (no direct equivalent)",
      "Promise.resolve(val) → asyncio.coroutine returning val or immediate return",
      "async () => { } (IIFE) → asyncio.run(async_main())"
    ],
    modules: [
      "import { X } from {./module.js} → from module import X",
      "import * as mod from {./module.js} → import module",
      "import mod from {./module.js} (default) → from module import default_export",
      "export default X → X at module level (use __all__ to restrict)",
      "export { X,Y } → __all__ = ['X','Y']",
      "export class Foo {} → class Foo: (public by default)",
      "index.js barrel → __init__.py with from .submodule import X",
      "package.json dependencies → requirements.txt or pyproject.toml",
      "npm install pkg → pip install pkg",
      "dynamic import({mod}) → importlib.import_module({mod})"
    ],
    async: [
      "async function fn() → async def fn(): (requires asyncio)",
      "await fetch(url) → async: await aiohttp.ClientSession().get(url) or sync: requests.get(url)",
      "await fs.promises.readFile(f) → async: await aiofiles.open(f) or sync: Path(f).read_text()",
      "Promise.all([p1,p2]) → await asyncio.gather(p1,p2)",
      "Promise.race([p1,p2]) → await asyncio.wait(tasks,return_when=FIRST_COMPLETED)",
      "Promise.allSettled(promises) → results=await asyncio.gather(*tasks,return_exceptions=True)",
      "new Promise((resolve,reject)=>{}) → loop.create_future() or asyncio.Future()",
      "setTimeout(fn,ms) → await asyncio.sleep(ms/1000)",
      "Worker threads → multiprocessing.Process or concurrent.futures.ProcessPoolExecutor",
      "AbortController/signal → asyncio.Task.cancel() or threading.Event",
      "event.on('data',cb) → asyncio.Queue or callback pattern",
      "setImmediate(fn) → await asyncio.sleep(0) (yield control)"
    ],
    versionNotes: [
      "Target Python 2.7: print stmt not fn, basestring not str, .iteritems() not .items(), urllib2, ConfigParser, no f-strings, no type hints",
      "Target Python 3.6: f-strings, type hints, async/await, pathlib, no walrus operator",
      "Target Python 3.8: Walrus operator (:=), positional-only params (/), f-string debugging (f'{x=}')",
      "Target Python 3.10: match/case (structural pattern matching), union types X|Y, ParamSpec",
      "Target Python 3.12: Type parameter syntax (def fn[T](x:T)), f-string any expression, improved error messages"
    ]
  },

  "java→csharp": {
    title: "Java → C#/.NET",
    stdlib: [
      "System.out.println(x) → Console.WriteLine(x)",
      "String.format(\"%s: %d\",a,b) → $\"{a}: {b}\" (interpolation)",
      "new SimpleDateFormat(\"yyyy-MM-dd\") → DateTime.Now.ToString(\"yyyy-MM-dd\")",
      "System.currentTimeMillis() → DateTimeOffset.UtcNow.ToUnixTimeMilliseconds()",
      "new Date() → DateTime.Now or DateTime.UtcNow",
      "Thread.sleep(ms) → await Task.Delay(ms) (async) or Thread.Sleep(ms)",
      "Integer.parseInt(s) → int.Parse(s) or int.TryParse(s,out var n)",
      "Double.parseDouble(s) → double.Parse(s)",
      "System.getenv(\"KEY\") → Environment.GetEnvironmentVariable(\"KEY\")",
      "Files.readString(Path.of(f)) → File.ReadAllText(f)",
      "Files.writeString(Path.of(f),s) → File.WriteAllText(f,s)",
      "Files.exists(Path.of(f)) → File.Exists(f)",
      "Paths.get(a,b) → Path.Combine(a,b)",
      "UUID.randomUUID() → Guid.NewGuid()",
      "Math.max/min/abs → Math.Max/Min/Abs (PascalCase)",
      "new ObjectMapper().readValue(s,T.class) → JsonSerializer.Deserialize<T>(s)",
      "new ObjectMapper().writeValueAsString(obj) → JsonSerializer.Serialize(obj)",
      "list.stream().filter(p).collect(toList()) → list.Where(p).ToList() (LINQ)",
      "new BufferedReader(new FileReader(f)) → File.ReadLines(f) or StreamReader",
      "System.err.println(x) → Console.Error.WriteLine(x)",
      "Arrays.asList(a,b,c) → new List<T>{a,b,c}",
      "Collections.unmodifiableList(list) → list.AsReadOnly()",
      "Pattern.compile(regex).matcher(s) → Regex.Match(s,pattern)"
    ],
    patterns: [
      "implements Interface → : IInterface (C# prefix I convention)",
      "extends Base → : Base (single colon for both)",
      "final field → readonly field",
      "final class → sealed class",
      "private String name + getName()/setName() → public string Name { get; set; } (auto-property)",
      "ArrayList<T> / List<T> → List<T> (System.Collections.Generic)",
      "HashMap<K,V> → Dictionary<K,V>",
      "HashSet<T> → HashSet<T>",
      "TreeMap<K,V> → SortedDictionary<K,V>",
      "Optional<T> → T? (nullable) or Nullable<T>",
      "opt.isPresent() → x != null / x is not null",
      "opt.orElse(def) → x ?? def (null coalescing)",
      "stream.filter(x->cond) → list.Where(x=>cond) (LINQ)",
      "stream.map(x->fn(x)) → list.Select(x=>fn(x)) (LINQ)",
      "stream.collect(Collectors.toList()) → .ToList()",
      "stream.forEach(x->{}) → foreach(var x in list) or list.ForEach()",
      "stream.reduce(id,acc) → list.Aggregate(id,(a,x)=>...)",
      "stream.anyMatch(pred) → list.Any(pred) (LINQ)",
      "stream.allMatch(pred) → list.All(pred) (LINQ)",
      "stream.sorted(Comparator) → list.OrderBy(x=>x.Prop) (LINQ)",
      "Collections.sort(list,comp) → list.Sort(comp) or list.OrderBy()",
      "new Comparator<T>(){compare(a,b){}} → (a,b)=>a.CompareTo(b)",
      "for (var entry : map.entrySet()) → foreach (var (key,val) in dict)",
      "@Override → override keyword",
      "@Deprecated → [Obsolete(\"message\")]",
      "instanceof → is pattern: if (x is Type t) { use t }",
      "try-with-resources → using statement: using var x = new R()",
      "throw new IllegalArgumentException → throw new ArgumentException",
      "catch(IOException|SQLException e) → catch(Exception e) when (e is IOException or SqlException)"
    ],
    modules: [
      "package com.app.service → namespace App.Service",
      "import java.util.List → using System.Collections.Generic",
      "import static → using static ClassName",
      "Maven/Gradle dependency → NuGet package reference"
    ],
    async: [
      "CompletableFuture<T> → Task<T>",
      "future.thenApply(fn) → await task; fn(result) or task.ContinueWith()",
      "CompletableFuture.allOf(futures) → Task.WhenAll(tasks)",
      "CompletableFuture.supplyAsync(()->val) → Task.Run(()=>val)",
      "ExecutorService → Task.Run or ThreadPool",
      "synchronized block → lock(obj) { } or SemaphoreSlim"
    ],
    versionNotes: [
      "Target .NET 6: Minimal API, top-level statements, file-scoped namespaces, global usings, record structs",
      "Target .NET 8: Primary constructors, collection expressions, default interface methods, required members, raw string literals",
      "Target .NET Framework 4.8: Full System.Web, ConfigurationManager, WCF, classic ASP.NET MVC",
      "Target .NET Core 3.1: No System.Web (use ASP.NET Core), IConfiguration instead of ConfigurationManager, dependency injection built-in"
    ]
  },

  "csharp→java": {
    title: "C#/.NET → Java",
    stdlib: [
      "Console.WriteLine(x) → System.out.println(x)",
      "$\"{a}: {b}\" (interpolation) → String.format(\"%s: %s\",a,b)",
      "DateTime.Now.ToString(fmt) → LocalDateTime.now().format(DateTimeFormatter.ofPattern(fmt))",
      "DateTimeOffset.UtcNow → Instant.now() (java.time)",
      "Thread.Sleep(ms) → Thread.sleep(ms)",
      "int.Parse(s) → Integer.parseInt(s)",
      "int.TryParse(s,out var n) → try{Integer.parseInt(s)}catch(NumberFormatException e){}",
      "File.ReadAllText(f) → Files.readString(Path.of(f)) (Java 11+)",
      "File.WriteAllText(f,s) → Files.writeString(Path.of(f),s)",
      "File.Exists(f) → Files.exists(Path.of(f))",
      "Path.Combine(a,b) → Paths.get(a,b).toString()",
      "Guid.NewGuid() → UUID.randomUUID()",
      "Environment.GetEnvironmentVariable(k) → System.getenv(k)",
      "JsonSerializer.Deserialize<T>(s) → new ObjectMapper().readValue(s,T.class)",
      "JsonSerializer.Serialize(obj) → new ObjectMapper().writeValueAsString(obj)",
      "list.Where(p).ToList() → list.stream().filter(p).collect(Collectors.toList())",
      "File.ReadLines(f) → Files.readAllLines(Path.of(f))",
      "Console.Error.WriteLine(x) → System.err.println(x)",
      "new List<T>{a,b,c} → List.of(a,b,c) (Java 9+)",
      "list.AsReadOnly() → Collections.unmodifiableList(list)",
      "Regex.Match(s,pat) → Pattern.compile(pat).matcher(s)"
    ],
    patterns: [
      ": IInterface → implements Interface (drop I prefix)",
      ": Base → extends Base",
      "sealed class → final class",
      "readonly field → final field",
      "public string Name {get;set;} → private String name + getName()/setName()",
      "auto-property {get;} → final field + getter",
      "List<T> (System.Collections) → ArrayList<T> or List<T> (java.util)",
      "Dictionary<K,V> → HashMap<K,V> or Map<K,V>",
      "SortedDictionary<K,V> → TreeMap<K,V>",
      "T? (nullable) → Optional<T> (Java 8+)",
      "x ?? default → Optional.ofNullable(x).orElse(default)",
      "x?.Property → Optional.ofNullable(x).map(o->o.getProperty())",
      "list.Where(x=>cond) → list.stream().filter(x->cond)",
      "list.Select(x=>fn(x)) → list.stream().map(x->fn(x))",
      "list.ToList() → .collect(Collectors.toList())",
      "list.Any(pred) → list.stream().anyMatch(pred)",
      "list.All(pred) → list.stream().allMatch(pred)",
      "list.OrderBy(x=>x.P) → list.stream().sorted(Comparator.comparing(x->x.getP()))",
      "list.Aggregate(init,(a,x)=>...) → list.stream().reduce(init,(a,x)->...)",
      "foreach(var x in list) → for(var x : list) (Java 10+ var)",
      "foreach(var (k,v) in dict) → for(var e:map.entrySet()){var k=e.getKey();var v=e.getValue();}",
      "is Type t (pattern) → instanceof Type t (Java 16+) or instanceof + cast",
      "using var x = new R() → try(var x = new R()) { } (try-with-resources)",
      "throw new ArgumentException → throw new IllegalArgumentException",
      "throw new ArgumentNullException → throw new NullPointerException",
      "catch when (condition) → catch then if(condition)",
      "record Foo(int X) → record Foo(int x) {} (Java 16+)",
      "[Obsolete] → @Deprecated",
      "delegate/event → listener interface + callback pattern",
      "LINQ to Objects → Java Stream API"
    ],
    modules: [
      "namespace App.Service → package com.app.service",
      "using System.Collections.Generic → import java.util.*",
      "using static → import static pkg.ClassName.*",
      "NuGet package → Maven/Gradle dependency"
    ],
    async: [
      "async Task<T> Method() → CompletableFuture<T> method()",
      "await task → future.join() (blocking) or .thenApply() (chained)",
      "Task.WhenAll(tasks) → CompletableFuture.allOf(futures)",
      "Task.Run(()=>val) → CompletableFuture.supplyAsync(()->val)",
      "lock(obj){} → synchronized(obj){} or ReentrantLock",
      "CancellationToken → volatile boolean flag or Future.cancel()"
    ],
    versionNotes: [
      "Target Java 8: Streams, lambdas, Optional, CompletableFuture, no var, no records, no switch expressions",
      "Target Java 11: var keyword, HttpClient, String methods (isBlank, strip, repeat), Files.readString",
      "Target Java 17: Records, sealed classes, pattern matching instanceof, text blocks, switch expressions",
      "Target Java 21: Virtual threads, record patterns, sequenced collections, string templates (preview)"
    ]
  },

  "java→python": {
    title: "Java → Python",
    stdlib: [
      "System.out.println(x) → print(x)",
      "String.format(\"%s: %d\",a,b) → f'{a}: {b}'",
      "Integer.parseInt(s) → int(s)",
      "Double.parseDouble(s) → float(s)",
      "new SimpleDateFormat(fmt).format(date) → datetime.now().strftime(fmt)",
      "LocalDateTime.now() → datetime.now()",
      "System.currentTimeMillis() → int(time.time()*1000)",
      "Thread.sleep(ms) → time.sleep(ms/1000)",
      "System.getenv(\"KEY\") → os.environ.get('KEY')",
      "Files.readString(Path.of(f)) → Path(f).read_text() (from pathlib)",
      "Files.writeString(Path.of(f),s) → Path(f).write_text(s)",
      "Files.exists(Path.of(f)) → Path(f).exists()",
      "Paths.get(a,b) → Path(a)/b or os.path.join(a,b)",
      "UUID.randomUUID() → uuid.uuid4()",
      "Math.max/min/abs → max()/min()/abs() (builtins)",
      "Collections.sort(list) → list.sort() or sorted(list)",
      "json via Jackson/Gson → json.loads(s) / json.dumps(obj)",
      "Jackson ObjectMapper → json module (json.loads/json.dumps)",
      "Arrays.asList(a,b) → [a,b] (literal list)",
      "Collections.unmodifiableList(l) → tuple(l) (immutable)",
      "list.stream().filter(p).map(f).collect(toList()) → [f(x) for x in list if p(x)]",
      "new HashMap<>() → dict()",
      "new ArrayList<>() → list()",
      "new HashSet<>() → set()",
      "StringBuilder → list.append()+str.join() or io.StringIO",
      "Pattern.compile(re).matcher(s).find() → re.search(re,s)"
    ],
    patterns: [
      "public class Foo { private int x; Foo(int x){this.x=x;} } → class Foo: def __init__(self,x): self.x=x",
      "public class w/ getters/setters → @dataclass class Foo: x:int (3.7+)",
      "record Foo(int x,String y) → @dataclass(frozen=True) class Foo: x:int; y:str",
      "this.x → self.x",
      "getX()/setX(v) → @property x / @x.setter or direct self.x",
      "private/protected/public → _ prefix convention (no enforcement)",
      "final → UPPER_CASE convention for constants",
      "static method → @staticmethod or @classmethod",
      "interface IFoo { } → class Foo(ABC): @abstractmethod",
      "implements Interface → class Foo(Interface): (multiple inheritance)",
      "extends Base → class Foo(Base):",
      "ArrayList<T>/List<T> → list (optionally list[T] hints)",
      "HashMap<K,V>/Map<K,V> → dict (optionally dict[K,V])",
      "HashSet<T> → set",
      "Optional<T> → None check or typing.Optional[T]",
      "opt.orElse(def) → x if x is not None else def",
      "stream.filter(p).map(f).collect(toList()) → [f(x) for x in items if p(x)]",
      "stream.forEach(x->{}) → for x in items: ...",
      "stream.anyMatch(pred) → any(pred(x) for x in items)",
      "stream.allMatch(pred) → all(pred(x) for x in items)",
      "for(var entry:map.entrySet()) → for k,v in d.items():",
      "for(int i=0;i<n;i++) → for i in range(n):",
      "instanceof Type → isinstance(x,Type)",
      "switch/case → match/case (3.10+) or if/elif",
      "try-with-resources → with statement",
      "try/catch/finally → try/except/finally",
      "throw new Exception(msg) → raise Exception(msg)",
      "null → None",
      "lambda x -> x+1 → lambda x: x+1",
      "enum Direction{N,S} → class Direction(Enum): N='N'; S='S'"
    ],
    modules: [
      "package com.app.service → directory structure app/service/",
      "import java.util.List → no import needed (list is builtin)",
      "import com.app.model.User → from app.model import User",
      "Maven/Gradle → pip requirements.txt or pyproject.toml"
    ],
    async: [
      "CompletableFuture<T> → async def fn() -> T: (asyncio)",
      "future.thenApply(fn) → result = await coro; fn(result)",
      "CompletableFuture.allOf(futures) → await asyncio.gather(*coros)",
      "ExecutorService → concurrent.futures.ThreadPoolExecutor",
      "synchronized → threading.Lock() or asyncio.Lock()"
    ],
    versionNotes: [
      "Target Python 3.6: f-strings, type hints (PEP 484), async/await, pathlib, dataclasses (3.7)",
      "Target Python 3.8: Walrus operator (:=), positional-only params, TypedDict, f'{x=}' debug",
      "Target Python 3.10: match/case, union X|Y syntax, ParamSpec, structural pattern matching",
      "Target Python 3.12: Type parameter syntax class Foo[T]:, f-string improvements, @override decorator"
    ]
  },

  "python→java": {
    title: "Python → Java",
    stdlib: [
      "print(x) → System.out.println(x)",
      "f'{a}: {b}' → String.format(\"%s: %s\",a,b)",
      "int(s) → Integer.parseInt(s)",
      "float(s) → Double.parseDouble(s)",
      "str(x) → String.valueOf(x)",
      "len(x) → x.size() (collections) or x.length() (strings) or x.length (arrays)",
      "datetime.now().strftime(fmt) → LocalDateTime.now().format(DateTimeFormatter.ofPattern(fmt))",
      "time.sleep(n) → Thread.sleep((long)(n*1000))",
      "os.environ.get('KEY') → System.getenv(\"KEY\")",
      "Path(f).read_text() → Files.readString(Path.of(f)) (Java 11+)",
      "Path(f).write_text(s) → Files.writeString(Path.of(f),s)",
      "Path(f).exists() → Files.exists(Path.of(f))",
      "os.path.join(a,b) → Paths.get(a,b).toString()",
      "uuid.uuid4() → UUID.randomUUID()",
      "max()/min()/abs() → Math.max()/Math.min()/Math.abs()",
      "sorted(list) → list.stream().sorted().collect(Collectors.toList())",
      "json.loads(s) → new ObjectMapper().readValue(s,Map.class) (Jackson)",
      "json.dumps(obj) → new ObjectMapper().writeValueAsString(obj)",
      "json module → Jackson ObjectMapper or Gson",
      "[a,b] (list literal) → List.of(a,b) (Java 9+) or Arrays.asList(a,b)",
      "tuple(l) (immutable) → Collections.unmodifiableList(l) or List.copyOf(l)",
      "[f(x) for x in items if p(x)] → items.stream().filter(p).map(f).collect(toList())",
      "dict() → new HashMap<>()",
      "list() → new ArrayList<>()",
      "set() → new HashSet<>()",
      "str.join(parts) → String.join(sep,parts) or StringBuilder",
      "re.search(pat,s) → Pattern.compile(pat).matcher(s).find()"
    ],
    patterns: [
      "class Foo: def __init__(self,x): self.x=x → public class Foo { private int x; public Foo(int x){this.x=x;} }",
      "@dataclass class Foo: x:int; y:str → public record Foo(int x,String y){} (Java 16+)",
      "self.x → this.x",
      "def method(self,a,b): → public ReturnType method(Type a,Type b) { } (add types)",
      "@staticmethod def fn(): → public static ReturnType fn() { }",
      "@property def name(self): → public String getName() { return this.name; }",
      "list → ArrayList<T> (must declare element type)",
      "dict → HashMap<K,V> (must declare key+value types)",
      "set → HashSet<T>",
      "tuple → custom record or List",
      "None → null or Optional<T> for returns",
      "[fn(x) for x in items if p(x)] → items.stream().filter(p).map(fn).collect(toList())",
      "for k,v in d.items(): → for(var e:map.entrySet()){var k=e.getKey();var v=e.getValue();}",
      "for i in range(n): → for(int i=0;i<n;i++)",
      "any(pred(x) for x in items) → items.stream().anyMatch(pred)",
      "isinstance(x,Type) → x instanceof Type",
      "match/case (3.10+) → switch expression (Java 14+)",
      "with open(f) as fh: → try(var r=new BufferedReader(new FileReader(f))){...}",
      "raise Exception(msg) → throw new RuntimeException(msg)",
      "lambda x: x+1 → (x)->x+1",
      "**kwargs → Map<String,Object> param or Builder pattern",
      "f'Hello {name}' → String.format(\"Hello %s\",name)",
      "x if cond else y → cond ? x : y",
      "class Direction(Enum): → enum Direction { N,S }",
      "ABC / @abstractmethod → interface or abstract class",
      "# type hints: x:int → explicit type: int x"
    ],
    modules: [
      "from app.model import User → import com.app.model.User",
      "from . import sibling → same-package import (no keyword needed)",
      "requirements.txt / pyproject.toml → pom.xml (Maven) or build.gradle",
      "__all__ = ['X'] → public/private access modifiers"
    ],
    async: [
      "async def fn(): → CompletableFuture<T> fn() { return supplyAsync(()->...); }",
      "await coro → future.join() (blocking) or .thenApply()",
      "asyncio.gather(*coros) → CompletableFuture.allOf(futures)",
      "concurrent.futures.ThreadPoolExecutor → Executors.newFixedThreadPool(n)",
      "threading.Lock() → synchronized or ReentrantLock"
    ],
    versionNotes: [
      "Target Java 8: Use streams for comprehensions, Optional for None, lambdas, no var keyword",
      "Target Java 11: var for local variables, HttpClient, Files.readString/writeString, String.isBlank()",
      "Target Java 17: Records for @dataclass, sealed classes for restricted inheritance, pattern matching",
      "Target Java 21: Virtual threads for async, record patterns, sequenced collections, unnamed variables _"
    ]
  },

  "javascript→typescript": {
    title: "JavaScript → TypeScript",
    stdlib: [
      "No API changes \u2014 TypeScript is a superset of JavaScript",
      "require({module}) → import module from {module} (ESM)",
      "module.exports = X → export default X",
      "exports.fn = fn → export function fn() {} or export { fn }",
      "require.resolve → import.meta.resolve (ESM)"
    ],
    patterns: [
      "function fn(a,b) → function fn(a: Type, b: Type): ReturnType",
      "const obj = {} → const obj: InterfaceName = {} (define interface)",
      "const arr = [] → const arr: Type[] = []",
      "callback(err,result) → Promise<T> with async/await",
      "any/untyped params → proper type annotations or generics",
      "== comparisons → === (strict equality)",
      "obj.dynamicProp → type with index signature: {[key:string]:Type}",
      "class with no types → add property types, method signatures",
      "JSON.parse(s) → JSON.parse(s) as Type (add type assertion)",
      "event handlers → properly typed: (e:MouseEvent)=>void",
      "switch without exhaustive → add never default for exhaustive switch",
      "null checks → strict null checks with ?. and ??"
    ],
    modules: [
      "require() → import (ESM syntax)",
      "module.exports → export default / named exports",
      ".js extension → .ts extension (compiles to .js)",
      "Add .d.ts for external untyped libs: declare module {lib}"
    ],
    async: [
      "Promise chains → async/await where cleaner",
      "Callback APIs → promisify + async/await with typed returns",
      "Promise<any> → Promise<SpecificType>"
    ],
    types: [
      "Define interfaces for ALL data shapes (params, returns, configs)",
      "Use type for unions: type Status = 'active'|'inactive'",
      "Use enum for fixed sets with semantic meaning",
      "Use generics: function first<T>(arr:T[]):T|undefined",
      "Use readonly for immutable properties",
      "Avoid 'any' \u2014 use 'unknown' + type guards",
      "Add return types to ALL functions (even void)",
      "Use Record<K,V> for key-value objects",
      "Use Partial<T>, Required<T>, Pick<T,K>, Omit<T,K>",
      "Use discriminated unions for state",
      "Use 'as const' for literal types"
    ],
    versionNotes: [
      "Target TS 4.x: Variadic tuple types, template literal types, key remapping in mapped types",
      "Target TS 5.0: Decorators (stage 3), const type parameters, enum improvements",
      "Target TS 5.6: Iterator helpers, disallowed nullish on non-nullable, strict builtin iterator checks"
    ]
  },

  "typescript→javascript": {
    title: "TypeScript → JavaScript (ES2024)",
    stdlib: [
      "No API changes \u2014 remove type system, keep runtime code",
      "import type { X } from {mod} → remove entirely (type-only)",
      "import { X, type Y } from {mod} → import { X } from {mod}"
    ],
    patterns: [
      "function fn(a:Type):RetType → function fn(a) (remove types)",
      "const x:Type = val → const x = val",
      "interface Foo { } → remove entirely (no runtime representation)",
      "type Foo = ... → remove entirely",
      "enum Dir { N='N',S='S' } → const Dir = Object.freeze({N:'N',S:'S'})",
      "x as Type → x (remove type assertion)",
      "generic <T>(arr:T[]):T → (arr) (remove generic params)",
      "readonly prop → no keyword (Object.freeze if needed)",
      "x! (non-null assertion) → x (remove !)",
      "x?.y / x ?? y → keep (valid JS)",
      "abstract class → regular class",
      "implements Interface → remove",
      "declare module/var → remove (ambient declarations)",
      "namespace Foo { } → plain object or module pattern",
      "satisfies Type → remove"
    ],
    modules: [
      ".ts extension → .js extension",
      "import type statements → remove entirely",
      "Keep all runtime import/export statements",
      ".d.ts files → delete (not needed)"
    ],
    async: [
      "async/await stays the same \u2014 valid JS",
      "Promise<T> return types → remove <T> annotation"
    ],
    versionNotes: [
      "Target ES5: Remove all TS features, convert class to prototype, arrow to function, const/let to var",
      "Target ES6: Keep classes, arrows, const/let, template literals — only remove types",
      "Target ES2020: Keep optional chaining (?.), nullish coalescing (??) — only remove types",
      "Target ES2024: Keep all modern JS features — only strip TypeScript type annotations"
    ]
  },
  // ═══ Java → Kotlin (Android-focused) ═══
  "java→kotlin": {
    title: "Java → Kotlin (Android)",
    stdlib: [
      "System.out.println(x) → println(x)",
      "String.format(fmt,args) → string templates: \u0024{expr} or fmt.format(args)",
      "Integer.parseInt(s) → s.toInt() / s.toIntOrNull()",
      "Double.parseDouble(s) → s.toDouble() / s.toDoubleOrNull()",
      "Collections.unmodifiableList(list) → list.toList() (returns read-only List)",
      "Collections.singletonList(x) → listOf(x)",
      "Arrays.asList(a,b,c) → listOf(a,b,c) or mutableListOf(a,b,c)",
      "new ArrayList<>() → mutableListOf<T>()",
      "new HashMap<>() → mutableMapOf<K,V>() or hashMapOf()",
      "new HashSet<>() → mutableSetOf<T>() or hashSetOf()",
      "map.put(k,v) → map[k] = v (operator overload)",
      "map.get(k) → map[k] (returns nullable T?)",
      "map.containsKey(k) → k in map",
      "list.get(i) → list[i]",
      "list.size() → list.size (property, no parentheses)",
      "str.length() → str.length (property)",
      "str.charAt(i) → str[i]",
      "str.substring(a,b) → str.substring(a,b) or str.slice(a..b)",
      "str.equals(other) → str == other (structural equality)",
      "str.equalsIgnoreCase(s) → str.equals(s, ignoreCase=true)",
      "obj == other (reference) → obj === other (referential equality)",
      "instanceof → is (smart cast: if (x is String) x.length works)",
      "(Type) obj cast → obj as Type / obj as? Type (safe cast)",
      "Object → Any / Any?",
      "void → Unit",
      "Void (boxed) → Nothing? or Unit",
      "final → val (immutable variable)",
      "Math.max(a,b) → maxOf(a,b) / kotlin.math.max(a,b)",
      "Math.min(a,b) → minOf(a,b)",
      "Math.abs(x) → kotlin.math.abs(x) or x.absoluteValue",
      "Thread.sleep(ms) → delay(ms) (suspend function, coroutines)",
      "System.currentTimeMillis() → System.currentTimeMillis() or Clock.System.now()",
      "Optional.of(x) → nullable type T? (no Optional needed)",
      "Optional.empty() → null",
      "optional.isPresent() → value != null",
      "optional.get() → value!! (non-null assertion) or value ?: default",
      "optional.orElse(def) → value ?: def (Elvis operator)",
      "try-with-resources → .use { } extension function",
      "synchronized(lock) {} → synchronized(lock) {} or Mutex (coroutines)",
      "Iterable.forEach(Consumer) → .forEach { } (trailing lambda)",
      "stream().map(fn) → .map { } (direct on collection, no stream())",
      "stream().filter(p) → .filter { }",
      "stream().collect(toList()) → .toList() or .toMutableList()",
      "stream().findFirst() → .firstOrNull()",
      "stream().anyMatch(p) → .any { }",
      "stream().allMatch(p) → .all { }",
      "stream().reduce() → .reduce() or .fold(initial) { }",
      "stream().flatMap() → .flatMap { }",
      "Collectors.toMap() → .associate { } or .associateBy { }",
      "Collectors.groupingBy() → .groupBy { }",
      "Collectors.joining(sep) → .joinToString(sep)"
    ],
    patterns: [
      "public class Foo {} → class Foo {} (public by default in Kotlin)",
      "private final String name; + getter → val name: String (read-only property)",
      "private String name; + getter + setter → var name: String (mutable property)",
      "POJO with getters/setters → data class Foo(val name: String, var age: Int)",
      "equals()/hashCode()/toString() boilerplate → data class (auto-generated)",
      "static final CONST = x → companion object { const val CONST = x }",
      "static method → companion object { fun method() } or top-level function",
      "static utility class → top-level functions in file (no class needed)",
      "Builder pattern → named parameters + default values: fun create(name: String, age: Int = 0)",
      "new Foo() → Foo() (no new keyword)",
      "anonymous inner class → object : Interface { } or lambda",
      "Comparator anonymous class → compareBy { it.field } or Comparator lambda",
      "enum with fields → enum class Status(val code: Int) { ACTIVE(1), INACTIVE(0) }",
      "sealed interface → sealed class/interface + data class subclasses",
      "switch-case → when (expr) { pattern -> result } (exhaustive for sealed)",
      "for (Type x : collection) → for (x in collection)",
      "for (int i=0;i<n;i++) → for (i in 0 until n) or repeat(n) { }",
      "while + iterator → for (item in iterable) or .forEach { }",
      "ternary a ? b : c → if (a) b else c (if is expression)",
      "null check if(x!=null) → x?.let { } or if (x != null) (smart cast)",
      "throw NPE on null → ?: throw or requireNotNull(x)",
      "multiple null checks → safe call chain: a?.b?.c?.d",
      "try-catch → try-catch (same, but runCatching { } also available)",
      "checked exceptions → no checked exceptions in Kotlin (@Throws for Java interop)",
      "interface + abstract methods → interface (can have default implementations)",
      "abstract class → abstract class (same concept)",
      "@Override → override keyword (mandatory, no annotation)",
      "String concatenation + → string template \u0024{expr} or \u0024var",
      "Type[] array → Array<Type> or IntArray/LongArray/etc for primitives",
      "varargs Type... → vararg param: Type",
      "Pair<A,B> → Pair(a,b) with destructuring: val (first, second) = pair",
      "Map.Entry<K,V> → destructuring in loop: for ((key, value) in map)",
      "singleton class → object Singleton { } (object declaration)",
      "lazy initialization → val x by lazy { expensive() }",
      "delegation pattern → class Foo(list: List<T>) : List<T> by list"
    ],
    android: [
      "// ═══ Android-Specific Migrations ═══",
      "Activity.findViewById(R.id.x) → ViewBinding: binding.x or Compose",
      "Fragment.onCreateView + inflate → ViewBinding or ComposeView in Fragment",
      "AsyncTask<P,Prog,R> → viewModelScope.launch { withContext(Dispatchers.IO) { } }",
      "AsyncTask.execute() → lifecycleScope.launch { } (lifecycle-aware)",
      "new Thread(runnable).start() → CoroutineScope.launch(Dispatchers.Default) { }",
      "Handler(Looper.getMainLooper()).post {} → withContext(Dispatchers.Main) { }",
      "runOnUiThread { } → withContext(Dispatchers.Main) { } inside coroutine",
      "IntentService → WorkManager for background work",
      "LocalBroadcastManager → SharedFlow / StateFlow / LiveData observer",
      "startActivityForResult() → registerForActivityResult(ActivityResultContracts.X())",
      "onActivityResult() → ActivityResultCallback in registerForActivityResult",
      "Loader/CursorLoader → ViewModel + Repository + Flow/LiveData",
      "ContentProvider direct query → Repository pattern + Room DAO",
      "SQLiteOpenHelper → Room Database + @Entity + @Dao + @Database",
      "SharedPreferences.edit().putX().apply() → DataStore<Preferences> (proto or preferences)",
      "PreferenceFragment → PreferenceFragmentCompat (AndroidX)",
      "android.support.v4.* → androidx.* (AndroidX migration)",
      "android.support.v7.* → androidx.appcompat.* / androidx.recyclerview.*",
      "AppCompatActivity (support) → AppCompatActivity (androidx.appcompat.app)",
      "RecyclerView.Adapter + ViewHolder → ListAdapter + DiffUtil (or LazyColumn in Compose)",
      "XML Layout + ConstraintLayout → Compose: Column/Row/Box + Modifier",
      "XML styles/themes → MaterialTheme + CompositionLocal in Compose",
      "XML menu + onOptionsItemSelected → TopAppBar actions in Compose",
      "XML navigation graph → Compose Navigation: NavHost + composable(route)",
      "Fragment transactions → Compose Navigation (no fragment manager)",
      "TabLayout + ViewPager2 → Compose HorizontalPager + TabRow",
      "AlertDialog.Builder → AlertDialog composable in Compose",
      "Toast.makeText() → Snackbar with SnackbarHost in Compose",
      "ProgressBar XML → CircularProgressIndicator() / LinearProgressIndicator()",
      "LiveData.observe(owner) { } → StateFlow + collectAsState() in Compose",
      "MutableLiveData.value = x → MutableStateFlow.value = x or mutableStateOf(x)",
      "ViewModel + LiveData → ViewModel + StateFlow + UiState sealed class (MVI)",
      "MVP: Presenter interface → ViewModel + UiState + UiEvent (MVVM/MVI)",
      "MVC: Activity doing everything → ViewModel + Repository + UseCase (Clean Arch)",
      "Dagger/Dagger-Android → Hilt (@HiltAndroidApp, @AndroidEntryPoint, @Inject)",
      "manual DI / ServiceLocator → Hilt modules (@Module, @Provides, @Singleton)",
      "Retrofit callback → Retrofit suspend fun + coroutines",
      "OkHttp Interceptor (Java) → OkHttp Interceptor (Kotlin, same API)",
      "Gson → Kotlin Serialization (@Serializable) or Moshi (KotlinJsonAdapterFactory)",
      "RxJava Observable/Single → Kotlin Flow / StateFlow / SharedFlow",
      "RxJava Schedulers → Coroutine Dispatchers (IO, Main, Default)",
      "RxJava CompositeDisposable → CoroutineScope cancellation (structured concurrency)",
      "EventBus → SharedFlow for events, StateFlow for state",
      "Butter Knife @BindView → ViewBinding or Compose (ButterKnife deprecated)",
      "Picasso/Glide (XML) → Coil (Compose: AsyncImage) or Glide Compose",
      "JUnit4 + Mockito → JUnit5 + MockK (Kotlin-first mocking)",
      "Espresso UI tests → Compose Testing: composeTestRule + onNodeWithText",
      "R.string.x → stringResource(R.string.x) in Compose",
      "getResources().getString() → context.getString() or stringResource() in Compose"
    ],
    modules: [
      "import com.pkg.Class; → import com.pkg.Class (same, but type alias available)",
      "static import → top-level function (no static import needed)",
      "Java source folder → Kotlin source folder (src/main/kotlin or src/main/java both work)",
      "build.gradle (Groovy) → build.gradle.kts (Kotlin DSL)",
      "apply plugin: X → plugins { id(X) } in Kotlin DSL",
      "compileSdkVersion 33 → compileSdk = 33 (Kotlin DSL property assignment)",
      "implementation X → implementation(X) in Kotlin DSL (parentheses)",
      "kapt X → ksp(X) (prefer KSP over KAPT for annotation processing)",
      "android.enableJetifier=true → remove if fully migrated to AndroidX"
    ],
    async: [
      "AsyncTask.doInBackground() → withContext(Dispatchers.IO) { }",
      "AsyncTask.onPostExecute() → result arrives in Main dispatcher (structured concurrency)",
      "AsyncTask.onProgressUpdate() → emit progress via Flow or StateFlow",
      "ExecutorService.submit() → async { } + await() in coroutine scope",
      "Future.get() (blocking) → Deferred.await() (suspending, non-blocking)",
      "CountDownLatch → suspendCancellableCoroutine or Channel",
      "Thread.sleep(ms) → delay(ms) (suspending, does not block thread)",
      "Callback<T> interface → suspend fun returning T directly",
      "Callback hell (nested) → sequential suspend calls (flat, readable)",
      "RxJava subscribeOn/observeOn → flowOn(Dispatchers.IO) / collect on Main",
      "Observable.create {} → flow { emit(value) } (cold Flow)",
      "BehaviorSubject → MutableStateFlow(initialValue)",
      "PublishSubject → MutableSharedFlow()",
      "Single.zip() → coroutineScope { async {} + async {} } then combine results",
      "RxJava .flatMap() → Flow .flatMapConcat { } / .flatMapMerge { }"
    ],
    versionNotes: [
      "Target Kotlin 1.5: Stable coroutines, value classes (@JvmInline), sealed interfaces",
      "Target Kotlin 1.6: Stable builder inference, suspend conversions, ksp improvements",
      "Target Kotlin 1.7: Opt-in annotations stable, min/maxOrNull, builder inference improvements",
      "Target Kotlin 1.8: JVM 1.8+ baseline, kotlin-reflect improvements, new JVM backend stable",
      "Target Kotlin 1.9: Kotlin/Wasm preview, ..<operator (rangeUntil), stable @ConsistentCopyVisibility, data object declarations, enum entries function",
      "Target Kotlin 2.0: K2 compiler (2x faster), stable smart casts in closures, new resolution algorithm, Compose compiler plugin bundled",
      "Target Kotlin 2.1: Guard conditions in when, multi-dollar string interpolation \u0024\u0024{}, non-local break/continue, improved K2 diagnostics"
    ]
  },
  // ═══ Kotlin → Java (Android reverse) ═══
  "kotlin→java": {
    title: "Kotlin → Java (Android)",
    stdlib: [
      "println(x) → System.out.println(x)",
      "string template \u0024{expr} → String.format() or concatenation",
      "s.toInt() / s.toIntOrNull() → Integer.parseInt(s) with try-catch",
      "listOf(a,b) → Collections.unmodifiableList(Arrays.asList(a,b)) or List.of(a,b) (Java 9+)",
      "mutableListOf<T>() → new ArrayList<T>()",
      "mutableMapOf<K,V>() → new HashMap<K,V>()",
      "map[k] = v → map.put(k, v)",
      "map[k] → map.get(k)",
      "k in map → map.containsKey(k)",
      "list.size (property) → list.size()",
      "str.length (property) → str.length()",
      "x is Type (smart cast) → instanceof + explicit cast",
      "x as Type / x as? Type → (Type) x with instanceof check",
      "Any / Any? → Object",
      "Unit → void",
      "val (immutable) → final modifier",
      "maxOf(a,b) / minOf(a,b) → Math.max(a,b) / Math.min(a,b)",
      "nullable T? → @Nullable T + Optional<T> or null checks",
      "value ?: default (Elvis) → value != null ? value : default",
      "x?.let { } → if (x != null) { /* use x */ }",
      "safe call a?.b?.c → nested null checks: if (a!=null && a.b!=null) a.b.c",
      ".use { } → try-with-resources: try (var r = resource) { }",
      ".map { } on collection → .stream().map(x -> ...).collect(toList())",
      ".filter { } → .stream().filter(x -> ...).collect(toList())",
      ".any { } → .stream().anyMatch(x -> ...)",
      ".firstOrNull() → .stream().findFirst().orElse(null)",
      ".associate { } → .stream().collect(Collectors.toMap(...))",
      ".groupBy { } → .stream().collect(Collectors.groupingBy(...))",
      ".joinToString(sep) → .stream().collect(Collectors.joining(sep))",
      "delay(ms) (suspend) → Thread.sleep(ms) or ScheduledExecutor"
    ],
    patterns: [
      "class Foo (public default) → public class Foo (explicit public)",
      "val name: String (property) → private final String name; + getName()",
      "var name: String → private String name; + getName() + setName()",
      "data class → class with equals/hashCode/toString/copy manually",
      "companion object { const val X } → public static final X",
      "companion object { fun x() } → public static method",
      "top-level function → static method in utility class",
      "object Singleton → singleton pattern (private constructor + static instance)",
      "named parameters → Builder pattern or method overloading",
      "default parameter values → method overloading: foo(), foo(a), foo(a,b)",
      "Foo() (no new) → new Foo()",
      "when (exhaustive) → switch-case (or if-else chain)",
      "for (x in collection) → for (Type x : collection)",
      "for (i in 0 until n) → for (int i=0; i<n; i++)",
      "if expression → ternary a ? b : c",
      "string template → String.format or + concatenation",
      "sealed class → abstract class + instanceof checks (or sealed interface Java 17+)",
      "enum class with properties → enum with fields + constructor",
      "override fun → @Override annotation",
      "vararg param → Type... param (varargs)",
      "destructuring val (a,b) = pair → pair.getFirst(); pair.getSecond()",
      "by lazy { } → lazy init with double-checked locking or Supplier",
      "extension function → static utility method with first param as receiver",
      "infix fun → regular method call: a.to(b) instead of a to b",
      "operator overload [] → explicit get()/set() methods"
    ],
    android: [
      "// ═══ Android Kotlin → Java reverse ═══",
      "ViewBinding binding.x → findViewById(R.id.x) or ViewBinding (Java supported)",
      "viewModelScope.launch { } → ExecutorService or AsyncTask (legacy) or RxJava",
      "lifecycleScope.launch { } → lifecycle observer + executor",
      "withContext(Dispatchers.IO) { } → Executors.newSingleThreadExecutor().submit()",
      "StateFlow.collectAsState() → LiveData.observe() in XML + ViewModel",
      "MutableStateFlow → MutableLiveData<T>",
      "Flow { emit() } → RxJava Observable.create() or LiveData",
      "Compose @Composable fun → XML layout + Fragment/Activity",
      "Compose Navigation → Navigation Component + Fragment destinations",
      "Compose LazyColumn → RecyclerView + Adapter + ViewHolder",
      "Hilt @Inject → Dagger @Inject or manual DI",
      "@AndroidEntryPoint → DaggerAppCompatActivity or manual component",
      "Kotlin Serialization → Gson or Jackson",
      "suspend fun apiCall() → Call<T> or Single<T> (RxJava)",
      "MockK mock → Mockito.mock(Class.class)"
    ],
    modules: [
      "import same as Java (fully compatible)",
      "build.gradle.kts → build.gradle (Groovy)",
      "plugins { id(X) } → apply plugin: X",
      "ksp(X) → annotationProcessor(X) or kapt(X)",
      "top-level functions file → public final class FileNameKt with static methods"
    ],
    async: [
      "coroutineScope { launch { } } → ExecutorService + Future",
      "async { } + await() → CompletableFuture (Java 8+) or Future.get()",
      "suspend fun → Callback<T> interface or CompletableFuture<T>",
      "flow { emit(x) } → Observable.create(emitter -> emitter.onNext(x))",
      "StateFlow → BehaviorSubject (RxJava) or MutableLiveData",
      "SharedFlow → PublishSubject (RxJava)",
      "flowOn(Dispatchers.IO) → .subscribeOn(Schedulers.io()).observeOn(AndroidSchedulers.mainThread())",
      "structured concurrency → manual cancellation with CompositeDisposable or executor shutdown",
      "Channel → BlockingQueue or RxJava Subject",
      "supervisorScope { } → independent try-catch per task with executor"
    ],
    versionNotes: [
      "Target Java 8: Lambdas, streams, CompletableFuture, Optional, method references, default methods",
      "Target Java 11: var (local), HttpClient, String methods (strip, isBlank, lines, repeat)",
      "Target Java 17: sealed classes, records, pattern matching instanceof, text blocks, switch expressions",
      "Target Java 21: Virtual threads, record patterns, sequenced collections, string templates (preview)"
    ]
  }
  ,
  "go→rust": {
    title: "Go → Rust (Systems)",
    stdlib: [
      "fmt.Println(x) → println!(\"{}\", x)",
      "fmt.Sprintf(\"%s %d\", a, b) → format!(\"{} {}\", a, b)",
      "strings.Contains(s, sub) → s.contains(sub)",
      "strings.Split(s, sep) → s.split(sep).collect::<Vec<&str>>()",
      "strings.Join(arr, sep) → arr.join(sep)",
      "strings.TrimSpace(s) → s.trim()",
      "strings.HasPrefix(s, p) → s.starts_with(p)",
      "strconv.Atoi(s) → s.parse::<i32>()",
      "strconv.Itoa(n) → n.to_string()",
      "len(slice) → slice.len()",
      "append(slice, x) → vec.push(x)",
      "make([]T, n) → Vec::with_capacity(n) or vec![T::default(); n]",
      "make(map[K]V) → HashMap::new()",
      "map[k] = v → map.insert(k, v)",
      "v, ok := map[k] → map.get(&k)",
      "delete(map, k) → map.remove(&k)",
      "os.Open(path) → File::open(path)?",
      "io.ReadAll(r) → read_to_string(&mut buf)?",
      "json.Marshal(v) → serde_json::to_string(&v)?",
      "json.Unmarshal(data, &v) → serde_json::from_str::<T>(&data)?",
      "time.Now() → Instant::now() or Utc::now() (chrono)",
      "time.Sleep(d) → thread::sleep(Duration::from_millis(ms))",
      "sort.Slice(s, less) → s.sort_by(|a, b| ...)",
      "math.Max(a, b) → a.max(b) or f64::max(a, b)"
    ],
    patterns: [
      "func name(params) retType { } → fn name(params) -> RetType { }",
      "type Struct struct { Field Type } → struct Struct { field: Type }",
      "method receiver func (s *Struct) Method() → impl Struct { fn method(&mut self) }",
      "interface { Method() } → trait Trait { fn method(&self); }",
      "struct embedding → composition with Deref or trait impl",
      "error return (val, error) → Result<Val, Error>",
      "if err != nil { return err } → ? operator",
      "defer f.Close() → Drop trait or explicit scope guard",
      "nil → None (Option<T>) or null pointer handling",
      "goroutine go func() { } → tokio::spawn(async { }) or thread::spawn",
      "channel ch := make(chan T) → tokio::sync::mpsc::channel",
      "select { case <-ch: } → tokio::select! { }",
      "sync.Mutex → std::sync::Mutex<T>",
      "sync.WaitGroup → tokio::task::JoinSet or futures::join_all",
      "for range slice → for item in &slice",
      "switch v.(type) { } → match or enum variants",
      "pointer *T → &T (reference) or Box<T> (owned)",
      "multiple return values → tuple or named struct",
      "init() function → lazy_static! or once_cell::Lazy"
    ],
    modules: [
      "package pkg → mod pkg (in mod.rs or pkg.rs)",
      "import \"pkg\" → use crate::pkg or use pkg_name",
      "exported (Uppercase) → pub modifier",
      "go.mod → Cargo.toml",
      "go get pkg → cargo add pkg"
    ],
    async: [
      "go func() { } → tokio::spawn(async move { })",
      "chan T → mpsc::Sender<T> / mpsc::Receiver<T>",
      "select { } → tokio::select! { }",
      "context.Context → CancellationToken or tokio::select with shutdown signal",
      "sync.Mutex → tokio::sync::Mutex for async, std::sync::Mutex for sync",
      "sync.RWMutex → tokio::sync::RwLock"
    ],
    types: [
      "int → i64, int32 → i32, int64 → i64",
      "float64 → f64, float32 → f32",
      "string → String (owned) or &str (borrowed)",
      "[]byte → Vec<u8> or &[u8]",
      "bool → bool",
      "[]T → Vec<T>",
      "map[K]V → HashMap<K, V>",
      "interface{} / any → Box<dyn Any> or generic T"
    ],
    versionNotes: [
      "Rust 2021 edition: use in closures, IntoIterator for arrays, disjoint captures",
      "Rust 1.75+: async fn in traits (RPITIT), impl Trait in more positions",
      "Use anyhow::Result for application code, thiserror for library errors"
    ]
  },
  "ruby→python": {
    title: "Ruby → Python",
    stdlib: [
      "puts x → print(x)",
      "p x → print(repr(x))",
      "x.to_s → str(x)",
      "x.to_i → int(x)",
      "x.to_f → float(x)",
      "arr.length / arr.size → len(arr)",
      "arr.push(x) / arr << x → arr.append(x)",
      "arr.map { |x| x*2 } → [x*2 for x in arr]",
      "arr.select { |x| x>0 } → [x for x in arr if x>0]",
      "arr.reject { |x| x<0 } → [x for x in arr if not x<0]",
      "arr.each { |x| } → for x in arr:",
      "arr.include?(x) → x in arr",
      "arr.flatten → [item for sub in arr for item in sub]",
      "arr.compact → [x for x in arr if x is not None]",
      "hash.each { |k,v| } → for k, v in dict.items():",
      "hash.keys → dict.keys()",
      "hash.merge(other) → {**dict, **other}",
      "str.gsub(pat, rep) → re.sub(pat, rep, str)",
      "str.split(sep) → str.split(sep)",
      "str.strip → str.strip()",
      "str.start_with?(x) → str.startswith(x)",
      "File.read(path) → open(path).read()",
      "File.open(path) { |f| } → with open(path) as f:",
      "JSON.parse(str) → json.loads(str)",
      "JSON.generate(obj) → json.dumps(obj)",
      "Time.now → datetime.datetime.now()",
      "raise StandardError → raise Exception()"
    ],
    patterns: [
      "class Foo; def initialize; end; end → class Foo: def __init__(self):",
      "attr_accessor :name → self.name = name (in __init__)",
      "attr_reader :name → @property def name(self):",
      "def method_name → def method_name(self):",
      "def self.class_method → @classmethod def class_method(cls):",
      "module Mixin → class Mixin: (multiple inheritance)",
      "include Module → class Foo(Module):",
      "begin; rescue; ensure; end → try: except: finally:",
      "block { |x| } → lambda x: or def callback(x):",
      "yield → callback()",
      "Proc.new / lambda → lambda or def",
      "nil → None",
      "true/false → True/False",
      "unless cond → if not cond:",
      "until cond → while not cond:",
      "x ||= default → x = x or default",
      "case/when → match/case (Python 3.10+) or if/elif",
      "symbol :name → string 'name' or enum",
      "do..end block → with statement or context manager"
    ],
    modules: [
      "require 'gem' → import module",
      "require_relative './file' → from . import file",
      "module Namespace → package (directory with __init__.py)",
      "Gemfile → requirements.txt or pyproject.toml",
      "gem install → pip install"
    ],
    async: [
      "Thread.new { } → threading.Thread(target=fn)",
      "Mutex.synchronize { } → with threading.Lock():",
      "EventMachine → asyncio",
      "Concurrent::Future → concurrent.futures.Future"
    ],
    versionNotes: [
      "Python 3.10+: match/case for pattern matching (replaces case/when)",
      "Python 3.9+: dict union operator |, type hints generics builtin",
      "Python 3.8+: walrus operator :=, f-strings = for debugging"
    ]
  },
  "php→python": {
    title: "PHP → Python",
    stdlib: [
      "echo $x → print(x)",
      "var_dump($x) → print(repr(x)) or pprint(x)",
      "strlen($s) → len(s)",
      "strpos($s, $sub) → s.find(sub)",
      "str_replace($old, $new, $s) → s.replace(old, new)",
      "explode($sep, $s) → s.split(sep)",
      "implode($sep, $arr) → sep.join(arr)",
      "trim($s) → s.strip()",
      "strtolower($s) → s.lower()",
      "strtoupper($s) → s.upper()",
      "substr($s, $start, $len) → s[start:start+length]",
      "array_push($arr, $x) → arr.append(x)",
      "array_merge($a, $b) → [*a, *b]",
      "array_map(fn, $arr) → list(map(fn, arr)) or [fn(x) for x in arr]",
      "array_filter($arr, fn) → list(filter(fn, arr)) or [x for x in arr if fn(x)]",
      "in_array($x, $arr) → x in arr",
      "array_key_exists($k, $arr) → k in dict",
      "count($arr) → len(arr)",
      "sort($arr) → arr.sort()",
      "json_encode($obj) → json.dumps(obj)",
      "json_decode($str, true) → json.loads(str)",
      "file_get_contents($path) → open(path).read()",
      "file_put_contents($path, $data) → open(path, 'w').write(data)",
      "preg_match($pat, $str, $m) → re.search(pat, str)",
      "preg_replace($pat, $rep, $str) → re.sub(pat, rep, str)",
      "date('Y-m-d') → datetime.date.today().isoformat()",
      "time() → int(time.time())",
      "intval($s) → int(s)",
      "floatval($s) → float(s)"
    ],
    patterns: [
      "class Foo { public function __construct() {} } → class Foo: def __init__(self):",
      "public/private/protected → convention: _private, __mangled",
      "static function → @staticmethod or @classmethod",
      "interface FooInterface → class FooInterface(ABC): @abstractmethod",
      "implements Interface → class Foo(Interface):",
      "extends Parent → class Child(Parent):",
      "namespace App\\Models → package (directory structure)",
      "use App\\Models\\User → from app.models import User",
      "try { } catch (Exception $e) { } → try: except Exception as e:",
      "$this->prop → self.prop",
      "self::CONST → cls.CONST or class-level constant",
      "new Foo() → Foo()",
      "=> (arrow in arrays) → : (in dicts)",
      "null → None",
      "true/false → True/False",
      "foreach ($arr as $k => $v) → for k, v in arr.items():",
      "foreach ($arr as $v) → for v in arr:",
      "list($a, $b) = $arr → a, b = arr",
      "?? (null coalescing) → or, or if x is not None",
      "?-> (nullsafe) → x.y if x else None"
    ],
    modules: [
      "require/include → import",
      "use Namespace\\Class → from namespace import Class",
      "composer.json → pyproject.toml or requirements.txt",
      "composer require → pip install",
      "autoload (PSR-4) → Python module system (__init__.py)"
    ],
    async: [
      "No native async → asyncio for async/await",
      "cURL multi → aiohttp or httpx async",
      "ReactPHP/Swoole → asyncio event loop",
      "pcntl_fork → multiprocessing.Process",
      "pthreads → threading.Thread"
    ],
    versionNotes: [
      "Python 3.10+: match/case, union types X|Y",
      "Python 3.9+: dict/list/tuple as generic types",
      "Python 3.8+: walrus operator, positional-only params"
    ]
  },
  "python→typescript": {
    title: "Python → TypeScript",
    stdlib: [
      "print(x) → console.log(x)",
      "len(x) → x.length",
      "str(x) → String(x) or x.toString()",
      "int(x) → parseInt(x, 10) or Number(x)",
      "float(x) → parseFloat(x) or Number(x)",
      "isinstance(x, T) → typeof x === 't' or x instanceof T",
      "type(x) → typeof x",
      "range(n) → Array.from({length: n}, (_, i) => i)",
      "list comprehension [x for x in arr] → arr.map(x => x) or arr.filter()",
      "dict comprehension {k:v for ...} → Object.fromEntries(...)",
      "x in list → list.includes(x)",
      "x in dict → key in obj or obj.hasOwnProperty(key)",
      "'sep'.join(arr) → arr.join('sep')",
      "s.split(sep) → s.split(sep)",
      "s.strip() → s.trim()",
      "s.startswith(x) → s.startsWith(x)",
      "s.endswith(x) → s.endsWith(x)",
      "s.lower() → s.toLowerCase()",
      "s.upper() → s.toUpperCase()",
      "s.replace(old, new) → s.replace(old, new) or s.replaceAll()",
      "json.dumps(obj) → JSON.stringify(obj)",
      "json.loads(str) → JSON.parse(str)",
      "os.path.join(a,b) → path.join(a, b)",
      "open(path).read() → fs.readFileSync(path, 'utf-8') or await fs.promises.readFile()",
      "datetime.now() → new Date()",
      "time.sleep(n) → await new Promise(r => setTimeout(r, n*1000))",
      "None → null or undefined",
      "True/False → true/false"
    ],
    patterns: [
      "class Foo: def __init__(self) → class Foo { constructor() }",
      "def method(self) → method(): ReturnType { }",
      "@property def x(self) → get x(): Type { }",
      "@staticmethod def x() → static x(): Type { }",
      "@classmethod def x(cls) → static x(): Type { }",
      "def func(a: int, b: str) -> bool → function func(a: number, b: string): boolean",
      "Optional[T] → T | null or T | undefined",
      "List[T] → T[] or Array<T>",
      "Dict[K,V] → Record<K,V> or Map<K,V>",
      "Tuple[A,B] → [A, B]",
      "Union[A,B] → A | B",
      "TypedDict → interface",
      "dataclass → interface + factory or class",
      "Enum → enum",
      "try: except E as e: → try { } catch (e: Error) { }",
      "raise Exception → throw new Error()",
      "with open() as f: → using try/finally or fs helpers",
      "lambda x: x*2 → (x: number) => x*2",
      "**kwargs → options: Record<string, unknown>",
      "*args → ...args: unknown[]"
    ],
    modules: [
      "import module → import module from 'module'",
      "from module import x → import { x } from 'module'",
      "from . import x → import { x } from './'",
      "requirements.txt → package.json",
      "pip install → npm install"
    ],
    async: [
      "async def func() → async function func(): Promise<T>",
      "await coroutine → await promise",
      "asyncio.gather(*tasks) → Promise.all([...tasks])",
      "asyncio.sleep(n) → await new Promise(r => setTimeout(r, n*1000))",
      "async for x in gen → for await (const x of gen)",
      "asyncio.Queue → custom async queue or p-queue"
    ],
    types: [
      "int → number",
      "float → number",
      "str → string",
      "bool → boolean",
      "bytes → Buffer or Uint8Array",
      "None → null | undefined",
      "Any → unknown or any",
      "list → Array<T>",
      "dict → Record<K,V>",
      "tuple → readonly [A, B]",
      "set → Set<T>"
    ],
    versionNotes: [
      "TypeScript 5.x: const type parameters, decorators, satisfies operator",
      "Use strict mode, noUncheckedIndexedAccess for safety",
      "Prefer interface over type for object shapes"
    ]
  },
  "go→python": {
    title: "Go → Python",
    stdlib: [
      "fmt.Println(x) → print(x)",
      "fmt.Sprintf(f, args) → f'...' or ''.format()",
      "strings.Contains(s, sub) → sub in s",
      "strings.Split(s, sep) → s.split(sep)",
      "strings.Join(arr, sep) → sep.join(arr)",
      "strings.TrimSpace(s) → s.strip()",
      "strconv.Atoi(s) → int(s)",
      "strconv.Itoa(n) → str(n)",
      "len(x) → len(x)",
      "append(s, x) → s.append(x)",
      "sort.Slice(s, less) → s.sort(key=...)",
      "json.Marshal(v) → json.dumps(v)",
      "json.Unmarshal(data, &v) → json.loads(data)",
      "os.Open(path) → open(path)",
      "io.ReadAll(r) → f.read()",
      "time.Now() → datetime.datetime.now()",
      "time.Sleep(d) → time.sleep(seconds)",
      "math.Max(a,b) → max(a,b)",
      "errors.New(msg) → Exception(msg) or ValueError(msg)"
    ],
    patterns: [
      "func name(params) retType → def name(params) -> retType:",
      "type Struct struct { } → class or dataclass",
      "method receiver (s *Struct) → def method(self):",
      "interface → ABC with @abstractmethod",
      "error return (val, err) → try/except or Result pattern",
      "if err != nil → try: except:",
      "defer f.Close() → with statement (context manager)",
      "nil → None",
      "goroutine go func() → threading.Thread or asyncio.create_task",
      "channel → queue.Queue or asyncio.Queue",
      "select { } → asyncio.wait or asyncio.gather",
      "sync.Mutex → threading.Lock()",
      "for range → for x in iterable:",
      "switch/case → match/case (3.10+) or if/elif",
      "pointer *T → regular reference (Python has no pointers)",
      "multiple return → tuple return",
      "struct embedding → class inheritance"
    ],
    modules: [
      "package pkg → module (file) in package (directory)",
      "import \"pkg\" → import pkg or from pkg import x",
      "exported Uppercase → public (Python convention: no underscore)",
      "unexported lowercase → private (convention: _prefix)",
      "go.mod → pyproject.toml or requirements.txt"
    ],
    async: [
      "goroutine → asyncio.create_task() or threading.Thread",
      "chan T → asyncio.Queue",
      "select { } → asyncio.gather or asyncio.wait",
      "sync.WaitGroup → asyncio.gather(*tasks)",
      "context.Context → asyncio timeout or threading Event"
    ],
    versionNotes: [
      "Python 3.10+: match/case for switch-like behavior",
      "Python 3.9+: builtin generic types (list[int] vs List[int])",
      "Use dataclasses for Go struct equivalents"
    ]
  },
  "rust→python": {
    title: "Rust → Python",
    stdlib: [
      "println!(\"{}\", x) → print(x)",
      "format!(\"{} {}\", a, b) → f'{a} {b}'",
      "s.len() → len(s)",
      "s.contains(sub) → sub in s",
      "s.split(sep) → s.split(sep)",
      "s.trim() → s.strip()",
      "s.starts_with(x) → s.startswith(x)",
      "s.parse::<i32>() → int(s)",
      "x.to_string() → str(x)",
      "vec.push(x) → list.append(x)",
      "vec.len() → len(list)",
      "vec.iter().map(f) → [f(x) for x in list] or map(f, list)",
      "vec.iter().filter(f) → [x for x in list if f(x)]",
      "vec.iter().any(f) → any(f(x) for x in list)",
      "vec.iter().all(f) → all(f(x) for x in list)",
      "HashMap::new() → {}",
      "map.insert(k, v) → dict[k] = v",
      "map.get(&k) → dict.get(k)",
      "map.contains_key(&k) → k in dict",
      "serde_json::to_string(&v) → json.dumps(v)",
      "serde_json::from_str(s) → json.loads(s)",
      "File::open(p)? → open(p)",
      "Instant::now() → time.time() or datetime.now()"
    ],
    patterns: [
      "fn name(params) -> Type → def name(params) -> Type:",
      "struct Foo { field: Type } → @dataclass class Foo: field: Type",
      "impl Foo { fn method(&self) } → class Foo: def method(self):",
      "trait Trait → class Trait(ABC): @abstractmethod",
      "impl Trait for Struct → class Struct(Trait):",
      "enum with variants → class Enum(enum.Enum) or Union types",
      "match expr { } → match expr: (Python 3.10+)",
      "Result<T, E> → try/except or return value",
      "Option<T> → Optional[T] or T | None",
      "? operator → try/except",
      "unwrap() → value (with assert or just use)",
      "Box<T> → regular Python object",
      "&T / &mut T → regular Python reference",
      "Vec<T> → list[T]",
      "HashMap<K,V> → dict[K,V]",
      "closure |x| x*2 → lambda x: x*2",
      "loop { } → while True:",
      "for x in iter → for x in iter:"
    ],
    modules: [
      "mod module → import module or from pkg import module",
      "use crate::module → from . import module",
      "pub → public (no prefix)",
      "Cargo.toml → pyproject.toml",
      "cargo add → pip install"
    ],
    async: [
      "tokio::spawn(async { }) → asyncio.create_task()",
      "async fn → async def",
      ".await → await",
      "tokio::select! → asyncio.wait",
      "mpsc::channel → asyncio.Queue"
    ],
    versionNotes: [
      "Python has no ownership/borrowing — just use normal references",
      "Python has GC — no need for lifetime annotations",
      "Use type hints for Rust-like type safety"
    ]
  }
};

export function getParadigmMap(sl, tl) {
  var key = sl + "→" + tl;
  return PARADIGM_MAPS[key] || null;
}
